#! /bin/bash
# Finds a file and opens it in okular if pdf and vim else

f=$(find $HOME -type f -name "*.pdf" | fzf)
if [ "$f" = "" ] ; then
    exit
fi
sway exec "zathura $f"
sway for_window [app_id="zathura"] move workspace 6
sway layout tabbed
